apiVersion: apps/v1
kind: Deployment
metadata:
  name: wish-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wish-app
  template:
    metadata:
      labels:
        app: wish-app
    spec:
      containers:
      - name: wish-app
        image: 633510959493.dkr.ecr.us-east-1.amazonaws.com/ete_project
        ports:
        - containerPort: 5000
